name: IS2SE
channels:
  - conda-forge
dependencies:
  - gdal
  - pip
  - rasterio
  - earthengine-api
  - geemap
  - leafmap
  - scikit-image
  - pandas
  - folium
  - sliderule
  - scipy
  - plotly
  - seaborn
  - loguru
  - pyarrow

